propel:

  client:
    torrent_id:
      type:             integer
      foreignTable:     torrent
      foreignReference: id
      onDelete:         cascade 

    created_at:
    updated_at:

    port:               integer
    bytes_uploaded:     integer
    bytes_downloaded:   integer
    bytes_left:         integer
    ip:                 varchar(40)  # maxlength of ip6 is 39 
    client_key:         varchar(60)  # should be big enough for a pack()
    tracker_id:         varchar(60)  # should be big enough for a pack() 

    peer_id:
      type:             varchar(60)  # should be big enough for a pack()
      #index:           unique       # SHOULD be unique, but replace this with an index of key+peer_id

    ##commenting this out to make it play better
    #_uniques:
    #  client_key_peer_id:  [client_key, peer_id, torrent_id]  # torrent is here just to make clients act less broken


  torrent:
    episode_id:
      type:             integer
      foreignTable:     episode 
      foreignReference: id
      onDelete:         cascade
      required:         false
      default:          null
    feed_id:
      type:             integer
      foreignTable:     feed 
      foreignReference: id
      onDelete:         cascade
      required:         false
      default:          null

    created_at:
    updated_at:

    file_name:      varchar(255)
    size:           integer            # file size
    mime_type:      varchar(40)
    web_url:        longvarchar        # for web backed torrents and non-torrent enclosure loving clients
    file_sha1:      varchar(40)        # for magnets
    guid_hash:                         # this is a sha1 of the guid from rss
      type:         varchar(40)
      index:        unique             # perhaps this index should also include podcast_id
    info_hash:                         # from the .torrent
      type:         varchar(40)

    # swarm state
    downloads:      integer            # may want to use a reflector script and increment this for web downloads todo
    seeders:        integer
    peers:          integer
    

  episode:
    podcast_id:
      type:             integer
      foreignTable:     podcast
      foreignReference: id
      onDelete:         cascade
      required:         false
      default:          null

    created_at:
    updated_at:

    title:          longvarchar
    slug:           varchar(255)
    description:    longvarchar
    length:         integer          # time
    downloads:      integer          # is this web downloads only? 
    guid_hash:      # we need this TODO?
      type:         varchar(40)
      index:        unique


  feed:
    podcast_id:
      type:             integer
      foreignTable:     podcast
      foreignReference: id
      onDelete:         cascade
      required:         false
      default:          null

    created_at:
    updated_at:

    tags:           longvarchar
    slug:           varchar(255)
    rss_url:        longvarchar
    rss_url_hash:   
      type:         varchar(40)
      index:        unique



  podcast:
    default_feed_id:
      type:             integer
      foreignTable:     feed
      foreignReference: id
      required:         false
      default:          null
      phpName:          DefaultFeed

    created_at:
    updated_at:

    title:            longvarchar
    slug:             varchar(255)
    description:      longvarchar
    last_fetched:     timestamp
    #todo add metas
