# default rules
root:
  url:   /
  param: { module: account, action: login }

homepage:
  url:   /admin
  param: { module: podcast, action: list }


settings:
  url:   /admin/settings
  param: { module: account, action: settings }


default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default:
  url:   /admin/:module/:action/*

podcast:
  url:   /:slug
  param: { module: podcast, action: view }

feed_default:
  url:   /feed/:podcast_slug/:format
  param: { module: feed, action: feed, slug: default }

feed:
  url:   /feed/:podcast_slug/:slug/:format
  param: { module: feed, action: feed }

episode:
  url:   /:podcast_slug/:slug
  param: { module: episode, action: view }
