prod:
  .settings:
    no_script_name:         on
    logging_enabled:        off

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              on
    cache:                  off
    no_script_name:         off
    etag:                   off

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  off
    web_debug:              off
    no_script_name:         off
    etag:                   off

all:
  .settings:
    standard_helpers:       [Partial, Cache, Form, Javascript, IconLinks, DeleteForm, PageTitle, ApacheConfig]
    # Form security secret (CSRF protection)
    csrf_secret:        <?php echo uniqid(),"\n" ?> # This value is regenerated every time the cache is refreshed.

    # Output escaping settings
    escaping_strategy:      false            # Determines how variables are made available to templates. Accepted values: on, off.
    escaping_method:        ESC_SPECIALCHARS # Function or helper used for escaping. Accepted values: ESC_RAW, ESC_ENTITIES, ESC_JS, ESC_JS_NO_ENTITIES, and ESC_SPECIALCHARS.

  .actions:
    error_404_module:       account  # To be called when a 404 error is raised
    error_404_action:       error404  # Or when the requested URL doesn't match any route

    login_module:           account   # To be called when a non-authenticated user
    login_action:           login     # Tries to access a secure page
