default:
  http_metas:
    content-type: text/html

  metas:
    description:  Web-enabled BitTorrent tracker
    keywords:     BitTorrent, bit torrent, feed, tracker, rss, limewire
    language:     en
    robots:       index, follow

  stylesheets:    [main]

  javascripts:    [prototype,forms,generateSlug]

  has_layout:     on
  layout:         layout
