default:
  http_metas:
    content-type: text/html

  metas:
    title:        |
                  <?php echo sfConfig::get('app_version_name'),'(', sfConfig::get('app_version_rev'), ')'; ?> @
                  hostnamehere
    description:  Web-enabled BitTorrent tracker
    keywords:     BitTorrent, bit torrent, feed, tracker, rss, limewire
    language:     en
    robots:       index, follow

  stylesheets:    [main]

  javascripts:    [prototype,forms]

  has_layout:     on
  layout:         layout
